### ISSUE TITLE
Thanks, a bug, and a question

### ISSUE THREAD

**Issue by kerim** [flegfleg/logseq-reminders-sync#1]
First of all, this is amazing. Thanks so much!

I noticed that even though I have a list named "Logseq" as defined in the configuration, it put my tasks in the "Inbox" list. 

Also, I'd like to modify the script to behave slightly differently. I'd like all Tasks marked as NOW or DOING with priority A to be synced, regardless of whether they have a date. Would that be difficult for me to change on my own?

**Comment by flegfleg** [comment]
Hi, your are welcome :) 

> I noticed that even though I have a list named "Logseq" as defined in the configuration, it put my tasks in the "Inbox" list.

Thanks for reporting this! I have pushed an update, you should get Version 1.1

> Also, I'd like to modify the script to behave slightly differently. I'd like all Tasks marked as NOW or DOING with priority A to be synced, regardless of whether they have a date. Would that be difficult for me to change on my own?

You would have to edit the query, it is defined in "**LogseqQueryTasksWithDeadlines**"near the top. There should be examples in the Logseq Forum for this. 

Best, Flo

**Comment by kerim** [comment]
Thanks. How do I update to v1.1? The link on the Code page still goes to version 1.0...

**Comment by flegfleg** [comment]
Ah, i thought the iCloud links would stay the same. I have updated them.

**Comment by kerim** [comment]
Working now (though only one of the links in the README seems to be correct).

And here is my updated query, which seems to work as well.

```
[:find (pull ?b [*])
            :where
            [?b :block/marker ?marker]
            [?b :block/priority "A"]
            [(contains? #{"NOW"} ?marker)]]
```

Thanks!
