### ISSUE TITLE
Feature request: no reminders for unscheduled items

### ISSUE THREAD

**Issue by kerim** [flegfleg/logseq-reminders-sync#3]
I have my shortcut set up to catch items listed as `NOW [#A]` - these are not scheduled (I only use scheduled for items marked LATER). Currently the plugin schedules these with a deadline/reminder of today at 9am in reminders. I'd rather not have these reminders. My thought is that the plugin could check if the item is scheduled or not before creating a reminder? Thanks.

**Comment by flegfleg** [comment]
Hi, I’d rather not complicate the shortcut with more options, it’s already pretty complex and hard to edit. 

You can easily remove the deadlines in the reminder creation step, try it and let me know if you are stuck.

**Comment by kerim** [comment]
Here?

<img width="602" alt="Screenshot 2023-12-27 at 7 35 24 PM" src="https://github.com/flegfleg/logseq-reminders-sync/assets/59976/5858294b-28c7-4fa4-ba90-31fa867754c8">

**Comment by flegfleg** [comment]
> Here?
> 
> <img alt="Screenshot 2023-12-27 at 7 35 24 PM" width="602" src="https://private-user-images.githubusercontent.com/59976/293024166-5858294b-28c7-4fa4-ba90-31fa867754c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2ODk1ODksIm5iZiI6MTcwMzY4OTI4OSwicGF0aCI6Ii81OTk3Ni8yOTMwMjQxNjYtNTg1ODI5NGItMjhjNy00ZmE0LWJhOTAtMzFmYTg2Nzc1NGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE1MDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNGZiMjRhOTQ5NTJlODJlMTI5ZDQ0ZTMwM2MyNjg0MzIzOGRhNWVmZmJjZDNhYjcyZmM3MTViNDNmZGFmNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J_OyvVQYRI_x66x5diqTcfpYoeCeXMHYJqF2Rre-Jm8">

Exactly

**Comment by flegfleg** [comment]
Hi Kerim, just a heads up: 
as my own workflow changed i added syncing of tasks marked as "NOW".

**Comment by kerim** [comment]
Thanks for letting me know!
