### ISSUE TITLE
support multiple logseq graph 

### ISSUE THREAD

**Issue by fakeyanss** [flegfleg/logseq-reminders-sync#5]
I have multiple Logseq graphs that need to sync todos. How can I configure and use them in a single shortcut?

<img width="606" alt="image" src="https://github.com/flegfleg/logseq-reminders-sync/assets/30440198/2f7472f2-8487-4416-be10-a3733fe5f73d">

**Comment by flegfleg** [comment]
Hi, habe you tried duplicating the shortcut and running it twice? You need to make sure that you sync each graph  to a different Reminders list (eg graph a, graph b). 

And test it with some dummy data first!
