### ISSUE TITLE
Add Priority

### ISSUE THREAD

**Issue by kerim** [flegfleg/logseq-reminders-sync#6]
Logseq has priorities: [#A], [#B], and [#C]
Reminders also has priorities:  High, Medium, and Low

I would like to request that the shortcut could also sync these to each other. For instance, importing something tagged [#A] as a High Priority task in Reminders.

The reason for this is that Reminders Smart Lists can use Priorities to filter tasks. 

Another option would be to simply add these as Reminders tags.

Thanks!

**Comment by flegfleg** [comment]
Hey Kerim,
since i am not using priorities and don't have the time to do it i can't implement it. 
Sorry!
